# Generated by Django 5.2.17 on 2026-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(db_index=True, max_length=40)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(max_length=60)),
                ('contenido', models.JSONField()),
                ('contexto', models.JSONField(help_text='Datos agregados enviados al modelo (sin identificadores)')),
                ('tokens_entrada', models.PositiveIntegerField()),
                ('tokens_salida', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'propuesta IA',
                'verbose_name_plural': 'propuestas IA',
                'ordering': ['-creada'],
            },
        ),
    ]
