# Generated by Django 5.2.17 on 2026-09-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.CharField(choices=[('configuracion', 'Configuración'), ('staging', 'Staging'), ('core', 'Core'), ('mart', 'Mart'), ('calidad', 'Calidad')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('hash_contenido', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=True, help_text='Falso si el archivo ya no existe')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'consulta SQL',
                'verbose_name_plural': 'consultas SQL',
                'ordering': ['archivo'],
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='en_curso', max_length=20)),
                ('incluye_carga_csv', models.BooleanField(default=False)),
                ('origen', models.CharField(default='web', max_length=20)),
            ],
            options={
                'verbose_name': 'ejecución',
                'verbose_name_plural': 'ejecuciones',
                'ordering': ['-iniciada'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField()),
                ('exitoso', models.BooleanField()),
                ('duracion_s', models.FloatField()),
                ('detalle', models.TextField(blank=True, help_text='Resumen del paso o mensaje de error')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.consultasql')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='pipeline.ejecucion')),
            ],
            options={
                'ordering': ['ejecucion', 'orden'],
            },
        ),
    ]
